on: push
name: Validate workdirs
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    name: Build ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: dind
            work-dir: /runner/_work
          - runs-on: dind-wd
            work-dir: /home/runner/work
          - runs-on: normal
            work-dir: /runner/_work
          - runs-on: normal-wd
            work-dir: /home/runner/work
    steps:
      - name: Check working directory
        run: |
          if [ "$PWD" == "${{ matrix.work-dir }}" ]
          then
            echo "PWD $PWD equals ${{ matrix.work-dir }}"
          else
            echo "PWD $PWD not equal to work dir ${{ matrix.work-dir }}"
          fi
